
**pandas**

**pandas series
a series is a one dimensional labeled arraycapable of holding any data type. the axis labels are collectively called the index**

**creating series**

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels =['a', 'b', 'c']
my_list = [10,23,45]
arr=np.array([ 32,43,56])
dic = {"name" : "satyendra", "age":24, "designation" : "ds"}

In [3]:
pd.Series(my_list, index=labels)

a    10
b    23
c    45
dtype: int64

In [4]:
pd.Series(arr, index=labels)

a    32
b    43
c    56
dtype: int32

In [5]:
pd.Series(dic)

name           satyendra
age                   24
designation           ds
dtype: object

**creating data frame**

In [6]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [7]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ['name',"age","city","salary"]
df2 = pd.DataFrame(data_list, columns = columns)

In [9]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
df2[['name','age','city']]

    name  age      city
0   John   28  New York
1   Anna   34     Paris
2  Peter   29    Berlin
3  Linda   42    London

**Create new columns**

In [7]:
df2['Designation'] = ['doctor', 'egn.','cm','mla']

In [8]:
df2

    name  age      city  salary Designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000        egn.
2  Peter   29    Berlin   62000          cm
3  Linda   42    London   85000         mla

**Deletion of columns**

In [9]:
df2.drop(['city','salary'],axis =1)

    name  age Designation
0   John   28      doctor
1   Anna   34        egn.
2  Peter   29          cm
3  Linda   42         mla

In [10]:
df2

    name  age      city  salary Designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000        egn.
2  Peter   29    Berlin   62000          cm
3  Linda   42    London   85000         mla

**remove row**

In [11]:
df2.drop(0,axis = 0)

    name  age    city  salary Designation
1   Anna   34   Paris   70000        egn.
2  Peter   29  Berlin   62000          cm
3  Linda   42  London   85000         mla

In [12]:
df2

    name  age      city  salary Designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000        egn.
2  Peter   29    Berlin   62000          cm
3  Linda   42    London   85000         mla

**selecting a row**

In [13]:
df2.loc[[0,1]]

   name  age      city  salary Designation
0  John   28  New York   65000      doctor
1  Anna   34     Paris   70000        egn.

df2.loc[3]

**selectin subset of row and columns**

In [18]:
df2.loc[[0,1]][['city','salary']]

       city  salary
0  New York   65000
1     Paris   70000

In [19]:
df2.iloc[[2,3]][['name', 'age']]

    name  age
2  Peter   29
3  Linda   42

In [20]:
df2.drop("Designation", axis= 1,inplace=True)

**Condition selction**

In [21]:
# i only want to see those people whose age is abovee 30

In [22]:
df2[df2['age']>30]

    name  age    city  salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [23]:
#I only want poeple whose age is above 30 and their city must be paris

In [24]:
df2[(df2['age']>30) &(df2['city'] == 'Paris')]

   name  age   city  salary
1  Anna   34  Paris   70000

In [25]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Finding missing data**

In [14]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df= pd.DataFrame(data)

In [15]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [28]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [29]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [30]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

**Removing missiing values depend on rows **

In [31]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [32]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

**filling the missing data**

In [33]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [34]:
values = {"A" : 0, "B" : 100,"C" : 300, "D" :123}
df.fillna(values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  123.0
2  0.0  3    3.0  123.0
3  4.0  4  300.0  123.0
4  5.0  5  300.0    5.0

In [35]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [36]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

**mergingjoiningconcatination**

**merging two data frame 2)concatination of 2 data frames 3) joining of two data frame**

In [4]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [5]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [6]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [7]:
pd.merge(employees,salaries)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [41]:
pd.merge(employees, salaries,on = 'employee_id', how ='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [42]:
pd.merge(employees, salaries,on = 'employee_id', how ='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [43]:
pd.merge(employees, salaries,on = 'employee_id', how ='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [44]:
pd.merge(employees, salaries,on = 'employee_id', how ='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

**Concatination**

In [45]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [46]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [47]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [48]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [49]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [50]:
pd.concat([df2,df1],axis = 1)

    A   B   C   A   B   C
0  A3  B3  C3  A0  B0  C0
1  A4  B4  C4  A1  B1  C1
2  A5  B5  C5  A2  B2  C2

**joining two data frame**

In [51]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [52]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [53]:
df2

   score
2     85
3     90
4     75

In [54]:
df1.join(df2,how='inner')

      name  score
2      Bob     85
3  Charlie     90

In [55]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [56]:
df1.join(df2,how='left')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [57]:
df1.join(df2,how='right')

      name  score
2      Bob     85
3  Charlie     90
4      NaN     75

**Groupby aggregation**

In [8]:
import numpy as np 
import pandas as pd

In [9]:


data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [10]:
#group by category and calculate the sum of salesabs
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [16]:
cat =df.groupby("Category")
cat
for i ,v in cat :
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [17]:
cat =df.groupby("Store")['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [18]:
cat =df.groupby("Category")['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [64]:
cat =df.groupby(["Category", "Store"])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

**Aggregation**

In [65]:
df["Sales"].mean()

187.5

In [66]:
df["Sales"].median()

190.0

In [67]:
df["Sales"].mode()

0    200
Name: Sales, dtype: int64

In [68]:
df["Sales"].min()

100

In [69]:
df["Sales"].mean()

187.5

In [70]:
df["Sales"].max()

300

In [71]:
df["Sales"].count()

8

In [72]:
df["Sales"].std()

66.06274074155351

In [73]:
df['Sales'].agg(["mean", "min","max","std","count","median"])

mean      187.500000
min       100.000000
max       300.000000
std        66.062741
count       8.000000
median    190.000000
Name: Sales, dtype: float64

**pivote Tables**

In [23]:


data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df= pd.DataFrame(data)
df['Quarter'] = 'Q' + df["Date"].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep Quarter
0  2023-01-01       A   East    176     91   John      Q1
1  2023-01-02       B   West    463     18   Mary      Q1
2  2023-01-03       C  North    666     49    Bob      Q1
3  2023-01-04       D  South    190     46  Alice      Q1
4  2023-01-05       A   East    667     45   John      Q1
5  2023-01-06       B   West    646     81   Mary      Q1
6  2023-01-07       C  North    925     32    Bob      Q1
7  2023-01-08       D  South    266     32  Alice      Q1
8  2023-01-09       A   East    753     92   John      Q1
9  2023-01-10       B   West    207     86   Mary      Q1
10 2023-01-11       C  North    571     32    Bob      Q1
11 2023-01-12       D  South    810     81  Alice      Q1
12 2023-01-13       A   East    617     30   John      Q1
13 2023-01-14       B   West    740     89   Mary      Q1
14 2023-01-15       C  North    952     45    Bob      Q1
15 2023-01-16       D  South    902     83  Alice      Q1
16 2023-01-17       A   East    188     76   John      Q1
17 2023-01-18       B   West    867     57   Mary      Q1
18 2023-01-19       C  North    830     24    Bob      Q1
19 2023-01-20       D  South    665     92  Alice      Q1

In [25]:
pd.pivot_table(df,values= "Sales", index="Region",columns="Product",aggfunc = 'std')

Product          A           B           C           D
Region
East     276.56229         NaN         NaN         NaN
North          NaN         NaN  165.377447         NaN
South          NaN         NaN         NaN  321.561503
West           NaN  257.408819         NaN         NaN

In [27]:
pivot2= pd.pivot_table(df,values= ["Sales", 'Units'] , index="Region",columns="Product",aggfunc = 'std')
pivot2
pivot2.fillna(0)

             Sales                                          Units             \
Product          A           B           C           D          A          B
Region
East     276.56229    0.000000    0.000000    0.000000  27.994642   0.000000
North      0.00000    0.000000  165.377447    0.000000   0.000000   0.000000
South      0.00000    0.000000    0.000000  321.561503   0.000000   0.000000
West       0.00000  257.408819    0.000000    0.000000   0.000000  29.743907


Product          C          D
Region
East      0.000000   0.000000
North    10.310189   0.000000
South     0.000000  26.185874
West      0.000000   0.000000

**cross table**

In [78]:
pd.crosstab( df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

**dataframe basic operations**

In [87]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [88]:
df1.shape

(5, 3)

In [89]:
df1.size

15

In [90]:
df1.head()

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [91]:
df1.tail()

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [92]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [93]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

df1.columns

In [97]:
df1['A'] +10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

**Data frame Applying Functions**

In [99]:
def square(x):
    return x*x

In [102]:
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [107]:
df1['C'].apply(lambda x : x-152)

0    -52
1     48
2    148
3    248
4    348
Name: C, dtype: int64

In [110]:
df1['D'] = df1['C'].apply(lambda x : x-152)
df1

   A   B    C    D
0  1  10  100  -52
1  2  20  200   48
2  3  30  300  148
3  4  40  400  248
4  5  50  500  348